# Generated by Django 5.1.7 on 2025-04-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='days_before_expiration',
            field=models.IntegerField(choices=[(1, '1 day before'), (3, '3 days before'), (5, '5 days before')], default=3, help_text='How many days before expiration would you like to be notified?'),
        ),
    ]
