# Generated by Django 5.1.7 on 2025-03-14 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('category', models.CharField(choices=[('PR', 'Produce'), ('GR', 'Grains'), ('DR', 'Dairy'), ('MS', 'Meat/Seafood'), ('DM', 'Deli Meats'), ('PF', 'Prepared Foods'), ('BE', 'Beverages'), ('CO', 'Condiments'), ('EG', 'Eggs'), ('OT', 'Other')], default='OT', max_length=2)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_expired', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
