# Generated by Django 5.1.7 on 2025-03-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fridgeitem',
            options={'verbose_name': 'Fridge Item', 'verbose_name_plural': 'Fridge Inventory'},
        ),
    ]
