# Generated by Django 5.1.7 on 2025-03-16 20:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("fridge", "0002_alter_fridgeitem_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fridge",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="fridge",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FridgeItemMyVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("expiration_date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PR", "Produce"),
                            ("GR", "Grains"),
                            ("DR", "Dairy"),
                            ("MS", "Meat/Seafood"),
                            ("DM", "Deli Meats"),
                            ("PF", "Prepared Foods"),
                            ("BE", "Beverages"),
                            ("CO", "Condiments"),
                            ("EG", "Eggs"),
                            ("OT", "Other"),
                        ],
                        default="OT",
                        max_length=2,
                    ),
                ),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_expired", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "fridge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fridge.fridge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fridge Item",
                "verbose_name_plural": "Fridge Inventory",
            },
        ),
    ]
