# Generated by Django 5.1.7 on 2025-03-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0002_alter_fridgeitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeitem',
            name='category',
            field=models.CharField(choices=[('PL', 'Please select a category (Required)'), ('PR', 'Produce'), ('GR', 'Grains'), ('DR', 'Dairy'), ('MS', 'Meat/Seafood'), ('DM', 'Deli Meats'), ('PF', 'Prepared Foods'), ('BE', 'Beverages'), ('CO', 'Condiments'), ('EG', 'Eggs'), ('OT', 'Other')], default='PL', max_length=2),
        ),
    ]
