# Generated by Django 5.1.7 on 2025-04-07 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0004_merge_20250406_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridgeitem',
            name='fridge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fridge.fridge'),
        ),
        migrations.DeleteModel(
            name='FridgeItemMyVersion',
        ),
    ]
