# Generated by Django 5.1.7 on 2025-04-20 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridge', '0005_fridgeitem_fridge_delete_fridgeitemmyversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeitem',
            name='fridge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fridge.fridge'),
            preserve_default=False,
        ),
    ]
